### ISSUE TITLE
Klarna Checkout & Selling from English store version

### ISSUE THREAD

**Issue by juhosyrj** [PrestaShop/klarnaofficial#1]
Currently there's no way to sell e.g. to Finland with KCO from English store version. We have multiple stores that sell to a single country using the country's native and English store versions. English store version forwards the customer to Prestashop's own checkout (/en/quick-order) which is a huge issue if the store has KCO as their only payment method. KCO can be initialized with locale 'en-gb' to all nordic and dach countries, so there's no restrictions from Klarna's end.

**Comment by Prestaworks** [comment]
This will be updated in future releases.
