### ISSUE TITLE
Rounding on order_list

### ISSUE THREAD

**Issue by Perfecticus** [PrestaShop/klarnaofficial#10]
Hi, I see that you noticed and fixed the rounding issues of order_list items about 2 months ago.
Is something stalling the release of a new module version to addons?

**Comment by Prestaworks** [comment]
It will be released when properly tested and approved for release on addons. But feel free to download the latest dev version and see if it fixes any rounding issues you experience.

**Comment by Perfecticus** [comment]
The issue I had was primarily a rounding issue on shipping vat.
It is fixed since the 2.1.7 commit.

Prestashop showed 9.80 for incl. vat 49 value, but the module used int cast on the 100*multiplied value which somehow resulted in 979.
Appeared to be consistent for any x9 value vat. E.g. 49 -> xx.79, 99 -> xx.79, where it should have been xx.80.

I believe what fixed that is the (string) cast instead of int.

**Comment by Perfecticus** [comment]
After further testing it appears rounding must be done explicitly on the $shipping_tax_value to avoid illegal format. You can replicate this by defining a shipping cost where the vat value would return 3 or more decimals.

During my testing I changed the excl. tax price from 55,2 to 55,22 with SE 25% VAT.
Gives a vat value of 13.805. Multiplied by 100, it still contains decimals.

![Bad format](https://puu.sh/EpLQb/63d7b721e1.png)

The previous int-cast protected it from hard errors, but resulted in rounding issues.
Now with only a string cast, the value may be a decimal value.

commonFeatures.php
```
[80]  $shipping_tax_value = $shipping_cost_with_tax - ($shipping_cost_with_tax / (1+($shipping_tax_rate/100)));
    + $shipping_tax_value = Tools::ps_round($shipping_tax_value, 2);
```

**Comment by Prestaworks** [comment]
Thanks, I have added it to 2.1.11
