### ISSUE TITLE
Problem with Klarna 1.9.9

### ISSUE THREAD

**Issue by MacRoy** [PrestaShop/klarnaofficial#4]
Hi!

I'm using Prestashop 1.6.1.15! And Klarna version 1.9.9 and I do not get a confirmation box on order as I received on the previous releases. Do you have any fix for this?

Best regards
MacRoy

**Comment by Prestaworks** [comment]
I Roy, what confirmation box are you refering to? Can you give me a screenshot?

**Comment by Kakelgiganten** [comment]
I have the same problem! And I also do not receive any confirmation e-mail.
![no confim](https://user-images.githubusercontent.com/33121475/32049828-d5dcf52e-ba4e-11e7-85a2-2bf7f6d00a59.jpg)

Everything looks ok in backend including the confirmation texts for the Klarna Module.

//David

**Comment by Prestaworks** [comment]
The Klarna module is not sending any emails, all emails sent are Prestashop default emails.

**Comment by Kakelgiganten** [comment]
So what.tpl file is loaded when that screen shows up?

**Comment by Prestaworks** [comment]
That tpl file is the thankyou.tpl from the built in controller, it is loaded because the push call has not been process properly yet.

**Comment by Kakelgiganten** [comment]
Thanks a lot 👍

**Comment by Kakelgiganten** [comment]
Hi again! Odd thing is that the URL when you successfully paid by Klarna is:

/sv/module/klarnaofficial/thankyou?sid=se

But on our old site it´s:
order-confirmation?key=3d58b687a4736a44017d0a14c34fc658&kcotp=1&sid=se&id_cart=3704&id_module=122

And on the old site it works! But on our new page its only loads the first example, which is odd?

Any clues?
