### ISSUE TITLE
Problem to configure Klarna 1.9.12

### ISSUE THREAD

**Issue by Kakelgiganten** [PrestaShop/klarnaofficial#5]
Error Messages when I try configure:
[PrestaShop] Fatal error in module file :/home/kakelgig/dev.kakelgiganten.se/modules/klarnaofficial/klarnaofficial.php:
Uncaught Error: Call to undefined method Tools::hash() in /home/kakelgig/dev.kakelgiganten.se/modules/klarnaofficial/klarnaofficial.php:466 Stack trace: #0 /home/kakelgig/dev.kakelgiganten.se/controllers/admin/AdminModulesController.php(867): KlarnaOfficial->getContent() #1 /home/kakelgig/dev.kakelgiganten.se/controllers/admin/AdminModulesController.php(1116): AdminModulesControllerCore->postProcessCallback() #2 /home/kakelgig/dev.kakelgiganten.se/classes/controller/Controller.php(178): AdminModulesControllerCore->postProcess() #3 /home/kakelgig/dev.kakelgiganten.se/classes/Dispatcher.php(367): ControllerCore->run() #4 /home/kakelgig/dev.kakelgiganten.se/admin654/index.php(58): DispatcherCore->dispatch() #5 {main} thrown

1.9.9 works fine

//David

**Comment by Prestaworks** [comment]
This is fixed in 1.9.13
