### ISSUE TITLE
Issue with Klarnaofficial and PS 1.7.2.4 and using alternative payment options

### ISSUE THREAD

**Issue by nils-sello** [PrestaShop/klarnaofficial#6]
Hi Prestaworks,

Nils on Sello here.
We have created an Prestashop webshop for a customer that will be using Prestashop 1.7.2.4 with KCO and also he is running Swish payments as a alternative payment method.

However it seems to be some trouble with the KCO module and PS 1.7.2.4. The alternative checkout in PS does not seem to work, it seems to be some issue with getting passed the step for choosing carrier when checking out the order. If you do not get passed that you will not be able to choose payment option and placing the order.

This happens both in Guest checkout and when doing a checkout with an account.

I have tested this in two different PS setups, the both PS setups used a custom template so I troubleshoot it also with changing the theme to "Classic" theme and it was the same results on all tries.

Why I think this is an issue in the Klarnaofficial module is because it works fine if I deactivate the module and runt the ordinary checkout.
However if I deactivate the Klarna module and do the checkout and go to the payment options but I do not place/finish the order. I then activate the Klarna module and then begin from the beginning go to the KCO checkout, choose alternative payment options and then go through the steps it works. But as fast as I logout or finish the order I will have the problem again with not being able to do the alternative checkout if Klarnaofficial module is active.

So my thoughts on this is that it is some trouble with the session, cookie and what country that is stored in the session with the Klarna module? And that interferes with the alternative checkout in PS 1.7.2.4.
I have never seen this issue with PS 1.6.

The webshop is: https://www.prylxperten.se/
We are running the newest version of Klarnaofficial module.
The problem is active right now so you can test it if you want. However I do not have any error logs for this problem so I do not have any proof to show.

The easiest way for you to troubleshoot this is probably if you have a PS 1.7.2.4 setup you can test this theory in? Maybe activate some alternative payment method like the bankwire module so you can see for yourself.

If you need any data from me about the webshop and the setup I can get that for you :)

Have a great day!

//Nils on Sello
Nils Muhrén
www.sello.io

![image](https://user-images.githubusercontent.com/8414273/34769560-6e5ce166-f5fe-11e7-841f-ca9532c578c8.png)

![image](https://user-images.githubusercontent.com/8414273/34769122-3c147cb0-f5fd-11e7-8f53-9e1cce0ad71d.png)

**Comment by Prestaworks** [comment]
The issue seems to be related to the table cart_products not being updated when adress is saved in the default checkout.
I will see if this will be adressed in future Prestashop releases as it feels more like an issue in Prestashop core and not the module.
