### ISSUE TITLE
KCO v3 problem

### ISSUE THREAD

**Issue by larsson68** [PrestaShop/klarnaofficial#8]
We got this problem when we try to activate Kco V3.

Client error: `POST https://api.klarna.com/checkout/v3/orders` resulted in a `401 Unauthorized` response: <html> <head><title>401 Authorization Required</title></head> <body bgcolor="white"> <center><h1>401 Authorization Re (truncated...)

Any clue ?

**Comment by Prestaworks** [comment]
Hi,

You are using the wrong credentials.
