### ISSUE TITLE
Notice: Undefined variable: shipping_state_id

### ISSUE THREAD

**Issue by mmsayeed** [PrestaShop/klarnaofficial#9]
Hello,
In my demo setup **(Prestashop 1.7.2.4)**  it shows "Notice Undefined variable: shipping_state_id
/module/klarnaofficial/thankyoukco?sid=se&klarna_order_id=ed11e8c7-7966-4a2e-adad-d0fb0e

Is there any fix for this, please?  Module Versions 2.0.8

**Comment by Prestaworks** [comment]
Hi,

There will be a fix for this, but you can always turn off error display in the shop (debug mode) so the notice is not displayd to the visitors.

**Comment by mmsayeed** [comment]
Hello,

Thank you very much. But when I turn off the debug mode the page shows **"HTTP ERROR 500"** Any Suggestions please?

**Comment by Prestaworks** [comment]
You can update with this file, https://github.com/PrestaShop/klarnaofficial/blob/1.7/klarnaofficial.php it should solve your issue.

**Comment by mmsayeed** [comment]
Sorry, This does not fix the issue. It is showing the http 500 error like the before on **thankyoukco** page
